Repository quintessences/heal-knowledge, pull requests merged in 2021-10, with the labels that each got.

#2 added description
  heal-knowledge.html
Labels: good first issue, hacktoberfest-accepted

#11 Add home icon on the header
  heal-knowledge.html
  images/home.png
  style.css
Labels: hacktoberfest-accepted

#23 Added hover effect in navbar links
  heal-knowledge.html
  style.css
Labels: hacktoberfest-accepted

#63 added vector background image in about section
  style.css
Labels: hacktoberfest
